sudo: false
language: android
jdk:
  - oraclejdk8

# INSTRUMENTED TESTS ARE DISABLED - until Google or Travis fix the mess with emulation, only local tests are enabled
#  - sys-img-armeabi-v7a-android-24
install:
# Travis still uses 'android' command behind the 'components' section update.
# That command is obsolete and cannot update Android SDK Tools after 25.2.5.
# Let's solve it here with the new command 'sdkmanager'
- yes | sdkmanager --verbose "build-tools;26.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-24"
- yes | sdkmanager --verbose "extras;android;m2repository"

# Check tools and dependencies installed
- yes | sdkmanager --list

#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - chmod +x ./wait_for_emulator.sh
#  - ./wait_for_emulator.sh
script:
# force init of adb way before any Gradle task that uses ADB; prevents a timeout error that skips emulators of android-24
  - adb devices
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
# run all the local unit tests of app module
  - ./gradlew :testDebug
# run all the instrumented tests of app module - DISABLED until we get an stable setup for Espresso in Travis
# - ./gradlew connectedDebugAndroidTest --info
# install app, then assemble and install instrumented tests of app module
#  - ./gradlew :installDebug
#  - ./gradlew :installDebugAndroidTest
# run sample instrumented unit test
#  - adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
env:
  global:
  - secure: h4Y7ZvgbvOj5T71ubRcw3Fy3KXF8qHugRFLGK3q2R9YuRsDAf8XH+Y/UiXyH8sac2QSj7Zlny1kA1DEJgwhTXs9wsAVKVJCQNTJGEvhm/4uQgPeNMzMv07Lqe8V+KUBsFH5qhfPJO357ERW0k2f2qljoLSHtHStclt7iGvFdynA=
  - secure: o9L6lXWpXowhQSdiUSmajliBUkQ6n7NrBUqhC09lqe7yXSGhEsgGRXqHoT3q2B4uIqGSiLCa9HQbW0dfDQCs+pADmzHIl3zbTViR88TSaIhOiTrqMUUl5iaO++pneZ2TzgU9bbGHbl6Ixjc6iALH2+F7P+RUM6vLTNPcfnCJa3g=
  - secure: ydxZrS7+1ht3p1tC6DE9W9bjLQGjMkwFBwyhNmcdEM6538kN8ZCBQe7NxSsCrC1nSDBLQ17Cziv0XJHl/pCfPrbkrPPgVFpjDfPeqC2zcGcCNcFQUEylXCvQ4uRU2hKL6dPqCsOQ57Pv3qwpPoprl/usoN5Wh8V7BKplU88ZaYM=
  matrix:
  - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
