sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
# first 'tools' updates SDK tools 'til last version ** in remote repository number 10 **
  - tools
# second 'tools' updates SDK tools 'til last version ** in remote repository number 11 ** (current last one)
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-24
  - sys-img-armeabi-v7a-android-24
branches:
  only:
  - master
before_install:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  -c 20M
- emulator -avd test -no-window &
- rm pom.xml
- android update project -p .
- chmod +x ./wait_for_emulator.sh
- ./wait_for_emulator.sh
script:
- ant clean
- ant debug
- cd test_client/tests
- ant acceptance-test
- cd ../..
- ./gradlew clean build
env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: epTZ0zZGDbHL3o6vSC9uNkZsi5j5SA6O/tvQBH7QW/dluuzIJxIjfhNbZHDyBReYDleirLzUFQpdWAUdvulCMLs/qZdIzFGlYXZSpxEnvPYMGQcilwADdJcxLw8L+3+ET5hSexxhjrTGw427IljkqGUpqQTxaLwFdFu98lDWSbc=
  matrix:
  - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
addons:
  coverity_scan:
    project:
      name: owncloud/android-library
      description: Build submitted via Travis CI
    notification_email: lukas@owncloud.com
    build_command_prepend: gradle clean
    build_command: gradle build
    branch_pattern: coverity_scan
